### ISSUE TITLE
TODO - Enhance Invoke-ExecuteNotebook

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellNotebook#26]
- [x] Catch and report errors 
- [x] Change `new parameters` to `injected-parameters` for New-CodeCell
- [x] If there are no cells tagged as `parameters` insert it at the beginning
- [x] Inject the new parameters only once, after the first
~~- [ ] Handle targets like arrays passed in the hashtable~~
- [x] If the cell has not `output.text`, need to create it
- [x] Support reading a notebook from a `URL`
